# Generated by Django 5.1.1 on 2024-09-21 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('toiletries', 'Toiletries'), ('linens', 'Linens'), ('room_supplies', 'Room Supplies')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.PositiveIntegerField(unique=True)),
                ('room_type', models.CharField(choices=[('standard', 'STANDARD'), ('deluxe', 'DELUXE'), ('suite', 'SUITE')], max_length=50)),
                ('availability', models.CharField(choices=[('BOOKED', 'BOOKED'), ('AVAILABLE', 'AVAILABLE')], default='AVAILABLE', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField(max_length=200)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('reorder_limit', models.PositiveIntegerField(default=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel_Mgmt.category')),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('booking_status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('CANCELLED', 'CANCELLED')], default='SUCCESS', max_length=15)),
                ('any_request', models.CharField(max_length=200)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel_Mgmt.room')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_stay', models.DurationField(default=0)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel_Mgmt.roombooking')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_role', models.CharField(choices=[('frontdesk', 'FrontDesk'), ('housekeeping', 'HouseKeeping'), ('management', 'Management')], max_length=50)),
                ('assigned_task', models.CharField(max_length=100)),
                ('task_status', models.BooleanField(default=False)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('staff_name', models.ForeignKey(limit_choices_to={'roles_choices': 'staff'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
