# Generated by Django 5.1.1 on 2024-09-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_Mgmt', '0003_suppliers_feedbackmodel_staffprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='user',
            new_name='staff_name',
        ),
    ]
