# Generated by Django 5.1.1 on 2024-09-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_Mgmt', '0004_rename_user_staffprofile_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
