# Generated by Django 5.1.1 on 2024-09-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_Mgmt', '0005_inventoryitem_reorder_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
