# Generated by Django 5.1.1 on 2024-09-16 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_Mgmt', '0006_staffprofile_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_name',
            field=models.ForeignKey(limit_choices_to={'roles_choices': 'staff'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
