# Generated by Django 5.1.1 on 2024-09-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_Mgmt', '0008_alter_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.CharField(default='AVAILABLE', max_length=10),
        ),
    ]
