# Generated by Django 5.1.1 on 2024-09-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_Mgmt', '0009_alter_room_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.CharField(choices=[('BOOKED', 'BOOKED'), ('AVAILABLE', 'AVAILABLE'), ('CANCELLED', 'CANCELLED')], default='AVAILABLE', max_length=10),
        ),
    ]
