# Generated by Django 5.1.1 on 2024-09-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_Mgmt', '0010_alter_room_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='booking_status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('CANCELLED', 'CANCELLED')], default='SUCCESS', max_length=15),
        ),
    ]
